package com.chatforia.android.auth

data class Language(
    val code: String,
    val name: String
)

val LANGUAGES =
    listOf(

        Language("af", "Afrikaans"),
        Language("ak", "Akan (Twi)"),
        Language("sq", "Albanian"),
        Language("am", "Amharic"),
        Language("ar", "Arabic"),
        Language("hy", "Armenian"),
        Language("as", "Assamese"),
        Language("ay", "Aymara"),
        Language("az", "Azerbaijani"),
        Language("bm", "Bambara"),
        Language("eu", "Basque"),
        Language("be", "Belarusian"),
        Language("bn", "Bengali"),
        Language("bho", "Bhojpuri"),
        Language("bs", "Bosnian"),
        Language("br", "Breton"),
        Language("bg", "Bulgarian"),
        Language("my", "Myanmar (Burmese)"),
        Language("ca", "Catalan"),
        Language("yue", "Cantonese"),
        Language("ceb", "Cebuano"),
        Language("zh-CN", "Chinese (Simplified)"),
        Language("zh-TW", "Chinese (Traditional)"),
        Language("co", "Corsican"),
        Language("hr", "Croatian"),
        Language("cs", "Czech"),
        Language("da", "Danish"),
        Language("prs", "Dari (Afghan Persian)"),
        Language("dv", "Dhivehi"),
        Language("nl", "Dutch"),
        Language("dz", "Dzongkha"),
        Language("en", "English"),
        Language("eo", "Esperanto"),
        Language("et", "Estonian"),
        Language("fi", "Finnish"),
        Language("fr", "French"),
        Language("fy", "Frisian"),
        Language("ff", "Fula"),
        Language("gl", "Galician"),
        Language("ka", "Georgian"),
        Language("de", "German"),
        Language("el", "Greek"),
        Language("gn", "Guarani"),
        Language("gu", "Gujarati"),
        Language("ht", "Haitian Creole"),
        Language("ha", "Hausa"),
        Language("haw", "Hawaiian"),
        Language("he", "Hebrew"),
        Language("hi", "Hindi"),
        Language("hmn", "Hmong"),
        Language("hu", "Hungarian"),
        Language("is", "Icelandic"),
        Language("ig", "Igbo"),
        Language("ilo", "Iloko"),
        Language("id", "Indonesian"),
        Language("ga", "Irish"),
        Language("it", "Italian"),
        Language("ja", "Japanese"),
        Language("jv", "Javanese"),
        Language("kn", "Kannada"),
        Language("kk", "Kazakh"),
        Language("km", "Khmer"),
        Language("rw", "Kinyarwanda"),
        Language("gom", "Konkani"),
        Language("kri", "Krio"),
        Language("ko", "Korean"),
        Language("ku", "Kurdish (Kurmanji)"),
        Language("ckb", "Kurdish (Sorani)"),
        Language("ky", "Kyrgyz"),
        Language("lo", "Lao"),
        Language("la", "Latin"),
        Language("lv", "Latvian"),
        Language("ln", "Lingala"),
        Language("lg", "Luganda"),
        Language("lt", "Lithuanian"),
        Language("lb", "Luxembourgish"),
        Language("mk", "Macedonian"),
        Language("mai", "Maithili"),
        Language("mg", "Malagasy"),
        Language("ms", "Malay"),
        Language("ml", "Malayalam"),
        Language("mt", "Maltese"),
        Language("mi", "Maori"),
        Language("mr", "Marathi"),
        Language("mni-Mtei", "Meiteilon (Manipuri)"),
        Language("mn", "Mongolian"),
        Language("zgh", "Moroccan"),
        Language("ne", "Nepali"),
        Language("nso", "Northern Sotho (Sepedi)"),
        Language("no", "Norwegian"),
        Language("oc", "Occitan"),
        Language("or", "Odia (Oriya)"),
        Language("om", "Oromo"),
        Language("pam", "Pampangan (Kapampangan)"),
        Language("pap", "Papiamento"),
        Language("ps", "Pashto"),
        Language("fa", "Persian"),
        Language("pl", "Polish"),
        Language("pt", "Portuguese"),
        Language("pa", "Punjabi"),
        Language("qu", "Quechua"),
        Language("ro", "Romanian"),
        Language("ru", "Russian"),
        Language("sm", "Samoan"),
        Language("sa", "Sanskrit"),
        Language("gd", "Scots Gaelic"),
        Language("sr", "Serbian"),
        Language("scn", "Sicilian"),
        Language("szl", "Silesian"),
        Language("sn", "Shona"),
        Language("sd", "Sindhi"),
        Language("si", "Sinhala"),
        Language("sk", "Slovak"),
        Language("sl", "Slovenian"),
        Language("so", "Somali"),
        Language("st", "Sesotho"),
        Language("ss", "Swati"),
        Language("es", "Spanish"),
        Language("su", "Sundanese"),
        Language("sw", "Swahili"),
        Language("sv", "Swedish"),
        Language("tl", "Tagalog"),
        Language("tg", "Tajik"),
        Language("ta", "Tamil"),
        Language("tt", "Tatar"),
        Language("te", "Telugu"),
        Language("tet", "Tetum"),
        Language("th", "Thai"),
        Language("bo", "Tibetan"),
        Language("ti", "Tigrinya"),
        Language("tpi", "Tok Pisin"),
        Language("to", "Tongan"),
        Language("tr", "Turkish"),
        Language("tk", "Turkmen"),
        Language("ts", "Tsonga"),
        Language("tn", "Tswana"),
        Language("ug", "Uyghur"),
        Language("uk", "Ukrainian"),
        Language("ur", "Urdu"),
        Language("uz", "Uzbek"),
        Language("vi", "Vietnamese"),
        Language("cy", "Welsh"),
        Language("wo", "Wolof"),
        Language("xh", "Xhosa"),
        Language("yi", "Yiddish"),
        Language("yo", "Yoruba"),
        Language("zu", "Zulu"),
    )
        .sortedBy { it.name }